defaultIndent: '    '
maximumIndentation: -1

modifyLineBreaks:
    textWrapOptions:
        columns: 100
        multipleSpacesToSingle: 1
        removeParagraphLineBreaks: 0
        
indentPreamble: 1
